version: '3'
services:
  app:
    build: .
    container_name: telegram_utdlp
    volumes:
      - telegram_utdlpdb:/app/base
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=sqlite:///app/db.db

volumes:
  telegram_utdlpdb:
